  File "images  File "images\swap_colors_icon.png"
  File "images  File "imageseset_colors_icon.png"
  File "images\select_all_child_layers_icon.png"
  File "imagesaluenode_icon.png"
  File "images\duplicate_icon.png"
  File "imagesbout_icon.png"
  File "images\synfig_icon.png"
  File "images\group_icon.png"
  File "images\jack_icon.png"
  File "images\sif_icon.png"
  File "images\keyframe_lock_past_on_icon.png"
  File "images\keyframe_lock_past_off_icon.png"
  File "images\keyframe_lock_future_on_icon.png"
  File "images\keyframe_lock_future_off_icon.png"
 File "imagesnimate_seek_next_keyframe_icon.png"
 File "imagesnimate_seek_prev_keyframe_icon.png"
 File "imagesnimate_seek_next_frame_icon.png"
 File "imagesnimate_seek_prev_frame_icon.png"
 File "imagesnimate_seek_begin_icon.png"
 File "imagesnimate_seek_end_icon.png"
 File "imagesnimate_play_icon.png"
 File "imagesnimate_stop_icon.png"
 File "imagesnimate_pause_icon.png"
 File "imagesnimate_loop_icon.png"
 File "imagesnimate_bounds_icon.png"
 File "imagesnimate_bound_lower_icon.png"
 File "imagesnimate_mode_off_icon.png"
 File "imagesnimate_bound_upper_icon.png"
  File "imagesename_icon.png"
 File "imagesnimate_mode_on_icon.png"
  File "images\set_fill_color.png"
  File "images\set_outline_color.png"
  File "images\duck_position_icon.png"
  File "images\duck_vertex_icon.png"
  File "images\duck_tangent_icon.png"
  File "images\duck_radius_icon.png"
  File "images\duck_width_icon.png"
  File "images\duck_angle_icon.png"
  File "images\show_grid_icon.png"
  File "images\snap_grid_icon.png"
  File "images\show_guideline_icon.png"
  File "images\snap_guideline_icon.png"
  File "images\onion_skin_icon.png"
  File "images\incr_resolution_icon.png"
  File "images\decr_resolution_icon.png"
  File "imagesender_options_icon.png"
  File "images\preview_options_icon.png"
  File "imagesackground_rendering_icon.png"
  File "imagesction_set_layer_description_icon.png"
  File "imagesction_add_to_set_icon.png"
  File "imagesction_remove_from_set_icon.png"
  File "imagesction_export_icon.png"
  File "imagesction_flat_interpolation_icon.png"
  File "imagesction_unexport_icon.png"
  File "imagesction_interpolate_interpolation_icon.png"
  File "imagesction_peak_interpolation_icon.png"
  File "imagesction_rounded_interpolation_icon.png"
  File "imagesction_squared_interpolation_icon.png"
 File "imagesction_doc_new_icon.png"
 File "imagesction_doc_open_icon.png"
 File "imagesction_doc_save_icon.png"
 File "imagesction_doc_saveas_icon.png"
 File "imagesction_doc_saveall_icon.png"
 File "images\interpolation_type_tcb_icon.png"
 File "imagesction_doc_redo_icon.png"
 File "imagesction_doc_undo_icon.png"
 File "images\interpolation_type_ease_icon.png"
 File "images\interpolation_type_const_icon.png"
 File "images\interpolation_type_linear_icon.png"
 File "images\interpolation_type_clamped_icon.png"
  File "images\layer_blur_blur_icon.png"
  File "images\layer_blur_motion_icon.png"
  File "images\layer_blur_radial_icon.png"
 File "imagesaluenode_forbidanimation_icon.png"
  File "images\layer_distortion_curvewarp_icon.png"
  File "images\layer_distortion_insideout_icon.png"
  File "images\layer_distortion_noise_icon.png"
  File "images\layer_distortion_stretch_icon.png"
  File "images\layer_distortion_spherize_icon.png"
  File "images\layer_distortion_twirl_icon.png"
  File "images\layer_distortion_warp_icon.png"
  File "images\layer_example_simplecircle_icon.png"
  File "images\layer_filter_clamp_icon.png"
  File "images\layer_example_metaballs_icon.png"
  File "images\layer_filter_colorcorrect_icon.png"
  File "images\layer_filter_halftone2_icon.png"
  File "images\layer_filter_halftone3_icon.png"
  File "images\layer_filter_lumakey_icon.png"
  File "images\layer_geometry_circle_icon.png"
  File "images\layer_geometry_checkerboard_icon.png"
  File "images\layer_fractal_julia_icon.png"
  File "images\layer_geometry_outline_icon.png"
  File "images\layer_fractal_mandelbrot_icon.png"
  File "images\layer_geometry_advanced_outline_icon.png"
  File "images\layer_geometry_polygon_icon.png"
  File "images\layer_geometry_rectangle_icon.png"
  File "images\layer_geometry_region_icon.png"
  File "images\layer_geometry_solidcolor_icon.png"
  File "images\layer_geometry_star_icon.png"
  File "images\layer_gradient_conical_icon.png"
  File "images\layer_gradient_curve_icon.png"
  File "images\layer_gradient_linear_icon.png"
  File "images\layer_gradient_noise_icon.png"
  File "images\layer_gradient_radial_icon.png"
  File "images\layer_other_duplicate_icon.png"
  File "images\layer_gradient_spiral_icon.png"
  File "images\layer_other_group_icon.png"
  File "images\layer_other_plant_icon.png"
  File "images\layer_other_stroboscope_icon.png"
 File "images\layer_other_importimage_icon.png"
  File "images\layer_other_supersample_icon.png"
  File "images\layer_other_skeleton_icon.png"
  File "images\layer_other_sound_icon.png"
  File "images\layer_other_switch_icon.png"
  File "images\layer_other_text_icon.png"
  File "images\layer_other_timeloop_icon.png"
  File "images\layer_other_xorpattern_icon.png"
  File "images\layer_stylize_bevel_icon.png"
  File "images\layer_stylize_shade_icon.png"
  File "images\layer_transform_translate_icon.png"
  File "images\layer_transform_rotate_icon.png"
  File "images\layer_transform_scale_icon.png"
  File "imagesesize_disabled_icon.png"
  File "imagesesize_up_left_icon.png"
  File "imagesesize_up_icon.png"
  File "imagesesize_up_right_icon.png"
  File "imagesesize_left_icon.png"
  File "imagesesize_right_icon.png"
  File "imagesesize_down_left_icon.png"
  File "imagesesize_down_icon.png"
  File "imagesesize_down_right_icon.png"
  File "imagesesize_transparent_icon.png"
  File "images	ool_brush_icon.png"
  File "images	ool_spline_icon.png"
  File "images	ool_cutout_icon.png"
  File "images	ool_skeleton_icon.png"
  File "images	ool_circle_icon.png"
  File "images	ool_draw_icon.png"
  File "images	ool_fill_icon.png"
  File "images	ool_eyedrop_icon.png"
  File "images	ool_gradient_icon.png"
  File "images	ool_mirror_icon.png"
  File "images	ool_normal_icon.png"
  File "images	ool_polyline_icon.png"
  File "images	ool_rectangle_icon.png"
  File "images	ool_rotate_icon.png"
  File "images	ool_sketch_icon.png"
  File "images	ool_smooth_move_icon.png"
  File "images	ool_scale_icon.png"
  File "images	ool_star_icon.png"
  File "images	ool_width_icon.png"
  File "images	ool_text_icon.png"
  File "images	ool_zoom_icon.png"
  File "images	ype_angle_icon.png"
  File "images	ype_splinepoint_icon.png"
  File "images	ype_bool_icon.png"
  File "images	ype_canvas_icon.png"
  File "images	ype_color_icon.png"
  File "images	ype_gradient_icon.png"
  File "images	ype_integer_icon.png"
  File "images	ype_list_icon.png"
  File "images	ype_real_icon.png"
  File "images	ype_string_icon.png"
  File "images	ype_time_icon.png"
  File "images	ype_vector_icon.png"
  File "images\library_icon.png"
  File "images\graphs_icon.png"
  File "images	ype_segment_icon.png"
 File "images  File "images\set_icon.png"
  File "images\history_icon.png"
  File "images\info_icon.png"
  File "images\keyframe_icon.png"
  File "images\layer_icon.png"
  File "images\meta_data_icon.png"
  File "images\palette_icon.png"
  File "images
avigator_icon.png"
  File "images\parameters_icon.png"
  File "images	ime_track_icon.png"
 File "images\utils_chain_link_on_icon.png"
 File "images\utils_chain_link_off_icon.png"
  File "images\utils_timetrack_align_icon.png"
  File "images\installer_logo.bmp"
  File "images\splash_screen.png"
  File "images\installer_logo_osx.png"
