  Delete "$INSTDIR\share\pixmaps\swap_colors_icon.png"
  Delete "$INSTDIR\share\pixmaps  Delete "$INSTDIR\share\pixmaps  Delete "$INSTDIR\share\pixmapseset_colors_icon.png"
  Delete "$INSTDIR\share\pixmaps\select_all_child_layers_icon.png"
  Delete "$INSTDIR\share\pixmapsaluenode_icon.png"
  Delete "$INSTDIR\share\pixmaps\duplicate_icon.png"
  Delete "$INSTDIR\share\pixmapsbout_icon.png"
  Delete "$INSTDIR\share\pixmaps\synfig_icon.png"
  Delete "$INSTDIR\share\pixmaps\group_icon.png"
  Delete "$INSTDIR\share\pixmaps\jack_icon.png"
  Delete "$INSTDIR\share\pixmaps\sif_icon.png"
  Delete "$INSTDIR\share\pixmaps\keyframe_lock_past_on_icon.png"
  Delete "$INSTDIR\share\pixmaps\keyframe_lock_past_off_icon.png"
  Delete "$INSTDIR\share\pixmaps\keyframe_lock_future_on_icon.png"
  Delete "$INSTDIR\share\pixmaps\keyframe_lock_future_off_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_next_keyframe_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_prev_keyframe_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_next_frame_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_prev_frame_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_begin_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_seek_end_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_play_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_stop_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_pause_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_loop_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_bounds_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_bound_lower_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_mode_off_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_bound_upper_icon.png"
  Delete "$INSTDIR\share\pixmapsename_icon.png"
 Delete "$INSTDIR\share\pixmapsnimate_mode_on_icon.png"
  Delete "$INSTDIR\share\pixmaps\set_fill_color.png"
  Delete "$INSTDIR\share\pixmaps\set_outline_color.png"
  Delete "$INSTDIR\share\pixmaps\duck_position_icon.png"
  Delete "$INSTDIR\share\pixmaps\duck_vertex_icon.png"
  Delete "$INSTDIR\share\pixmaps\duck_tangent_icon.png"
  Delete "$INSTDIR\share\pixmaps\duck_radius_icon.png"
  Delete "$INSTDIR\share\pixmaps\duck_width_icon.png"
  Delete "$INSTDIR\share\pixmaps\duck_angle_icon.png"
  Delete "$INSTDIR\share\pixmaps\show_grid_icon.png"
  Delete "$INSTDIR\share\pixmaps\snap_grid_icon.png"
  Delete "$INSTDIR\share\pixmaps\show_guideline_icon.png"
  Delete "$INSTDIR\share\pixmaps\snap_guideline_icon.png"
  Delete "$INSTDIR\share\pixmaps\onion_skin_icon.png"
  Delete "$INSTDIR\share\pixmaps\incr_resolution_icon.png"
  Delete "$INSTDIR\share\pixmaps\decr_resolution_icon.png"
  Delete "$INSTDIR\share\pixmapsender_options_icon.png"
  Delete "$INSTDIR\share\pixmaps\preview_options_icon.png"
  Delete "$INSTDIR\share\pixmapsackground_rendering_icon.png"
  Delete "$INSTDIR\share\pixmapsction_set_layer_description_icon.png"
  Delete "$INSTDIR\share\pixmapsction_add_to_set_icon.png"
  Delete "$INSTDIR\share\pixmapsction_remove_from_set_icon.png"
  Delete "$INSTDIR\share\pixmapsction_export_icon.png"
  Delete "$INSTDIR\share\pixmapsction_flat_interpolation_icon.png"
  Delete "$INSTDIR\share\pixmapsction_unexport_icon.png"
  Delete "$INSTDIR\share\pixmapsction_interpolate_interpolation_icon.png"
  Delete "$INSTDIR\share\pixmapsction_peak_interpolation_icon.png"
  Delete "$INSTDIR\share\pixmapsction_rounded_interpolation_icon.png"
  Delete "$INSTDIR\share\pixmapsction_squared_interpolation_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_new_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_open_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_save_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_saveas_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_saveall_icon.png"
 Delete "$INSTDIR\share\pixmaps\interpolation_type_tcb_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_redo_icon.png"
 Delete "$INSTDIR\share\pixmapsction_doc_undo_icon.png"
 Delete "$INSTDIR\share\pixmaps\interpolation_type_ease_icon.png"
 Delete "$INSTDIR\share\pixmaps\interpolation_type_const_icon.png"
 Delete "$INSTDIR\share\pixmaps\interpolation_type_linear_icon.png"
 Delete "$INSTDIR\share\pixmaps\interpolation_type_clamped_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_blur_blur_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_blur_motion_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_blur_radial_icon.png"
 Delete "$INSTDIR\share\pixmapsaluenode_forbidanimation_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_curvewarp_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_insideout_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_noise_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_stretch_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_spherize_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_twirl_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_distortion_warp_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_example_simplecircle_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_filter_clamp_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_example_metaballs_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_filter_colorcorrect_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_filter_halftone2_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_filter_halftone3_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_filter_lumakey_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_circle_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_checkerboard_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_fractal_julia_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_outline_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_fractal_mandelbrot_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_advanced_outline_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_polygon_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_rectangle_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_region_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_solidcolor_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_geometry_star_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_conical_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_curve_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_linear_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_noise_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_radial_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_duplicate_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_gradient_spiral_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_group_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_plant_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_stroboscope_icon.png"
 Delete "$INSTDIR\share\pixmaps\layer_other_importimage_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_supersample_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_skeleton_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_sound_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_switch_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_text_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_timeloop_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_other_xorpattern_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_stylize_bevel_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_stylize_shade_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_transform_translate_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_transform_rotate_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_transform_scale_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_disabled_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_up_left_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_up_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_up_right_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_left_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_right_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_down_left_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_down_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_down_right_icon.png"
  Delete "$INSTDIR\share\pixmapsesize_transparent_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_brush_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_spline_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_cutout_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_skeleton_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_circle_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_draw_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_fill_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_eyedrop_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_gradient_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_mirror_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_normal_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_polyline_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_rectangle_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_rotate_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_sketch_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_smooth_move_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_scale_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_star_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_width_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_text_icon.png"
  Delete "$INSTDIR\share\pixmaps	ool_zoom_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_angle_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_splinepoint_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_bool_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_canvas_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_color_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_gradient_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_integer_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_list_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_real_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_string_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_time_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_vector_icon.png"
  Delete "$INSTDIR\share\pixmaps\library_icon.png"
  Delete "$INSTDIR\share\pixmaps\graphs_icon.png"
  Delete "$INSTDIR\share\pixmaps	ype_segment_icon.png"
 Delete "$INSTDIR\share\pixmaps  Delete "$INSTDIR\share\pixmaps\set_icon.png"
  Delete "$INSTDIR\share\pixmaps\history_icon.png"
  Delete "$INSTDIR\share\pixmaps\info_icon.png"
  Delete "$INSTDIR\share\pixmaps\keyframe_icon.png"
  Delete "$INSTDIR\share\pixmaps\layer_icon.png"
  Delete "$INSTDIR\share\pixmaps\meta_data_icon.png"
  Delete "$INSTDIR\share\pixmaps\palette_icon.png"
  Delete "$INSTDIR\share\pixmaps
avigator_icon.png"
  Delete "$INSTDIR\share\pixmaps\parameters_icon.png"
  Delete "$INSTDIR\share\pixmaps	ime_track_icon.png"
 Delete "$INSTDIR\share\pixmaps\utils_chain_link_on_icon.png"
 Delete "$INSTDIR\share\pixmaps\utils_chain_link_off_icon.png"
  Delete "$INSTDIR\share\pixmaps\utils_timetrack_align_icon.png"
  Delete "$INSTDIR\share\pixmaps\installer_logo.bmp"
  Delete "$INSTDIR\share\pixmaps\splash_screen.png"
  Delete "$INSTDIR\share\pixmaps\installer_logo_osx.png"
